name: Docker custom action

on:
  workflow_dispatch:
  push:
  
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-s3-docker/
